# Generated by Django 3.1.4 on 2020-12-31 17:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(default=datetime.datetime(2020, 12, 31, 17, 44, 56, 862357))),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=20)),
                ('iso_country_code', models.CharField(max_length=5)),
                ('occupation', models.CharField(blank=True, max_length=40)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
